import type { IconType } from "react-icons";
import {
  SiPython,
  SiReact,
  SiDocker,
  SiKubernetes,
  SiTypescript,
  SiJavascript,
  SiApacheairflow,
  SiApachespark,
  SiApachekafka,
  SiSnowflake,
  SiTrino,
  SiDjango,
  SiFastapi,
  SiNodedotjs,
  SiGraphql,
  SiTensorflow,
  SiScikitlearn,
  SiPostgresql,
  SiDatabricks,
  SiAnthropic,
  SiGooglegemini,
  SiGooglecloud,
  SiCplusplus,
  SiGnubash,
  SiGrafana,
  SiSplunk,
  SiSentry,
  SiGithubactions,
  SiJenkins,
  SiSpringboot,
  SiMysql,
  SiFirebase,
  SiRedis,
  SiPandas,
} from "react-icons/si";
import { FaAws, FaJava } from "react-icons/fa";

// Map of lowercased tech name -> brand icon. Names not present fall back to a dot.
const map: Record<string, IconType> = {
  python: SiPython,
  react: SiReact,
  "react native": SiReact,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  typescript: SiTypescript,
  javascript: SiJavascript,
  "apache airflow": SiApacheairflow,
  airflow: SiApacheairflow,
  "apache spark": SiApachespark,
  spark: SiApachespark,
  kafka: SiApachekafka,
  snowflake: SiSnowflake,
  trino: SiTrino,
  django: SiDjango,
  fastapi: SiFastapi,
  "node.js": SiNodedotjs,
  graphql: SiGraphql,
  tensorflow: SiTensorflow,
  "scikit-learn": SiScikitlearn,
  postgresql: SiPostgresql,
  databricks: SiDatabricks,
  "anthropic claude sdk": SiAnthropic,
  "google adk": SiGooglegemini,
  aws: FaAws,
  java: FaJava,
  "c++": SiCplusplus,
  bash: SiGnubash,
  grafana: SiGrafana,
  splunk: SiSplunk,
  sentry: SiSentry,
  "github actions": SiGithubactions,
  jenkins: SiJenkins,
  "spring boot": SiSpringboot,
  mysql: SiMysql,
  firebase: SiFirebase,
  redis: SiRedis,
  pandas: SiPandas,
  gcp: SiGooglecloud,
};

export function techIcon(name: string): IconType | null {
  return map[name.trim().toLowerCase()] ?? null;
}
